Add EXM130 module
projecttacoma/synthea pull request #2
Opened 2019-12-03 17:36 UTC by mayerm94

2019-12-03 17:53 UTC, lukoktonos approved these changes

2019-12-04 16:24 UTC, mgramigna requested changes
Can we include the updated `synthea.properties` file from the bundle calculator as part of this PR as well? I think it has some config that we want like using STU3 export instead of R4

2019-12-04 16:28 UTC, mayerm94 commented
> Can we include the updated `synthea.properties` file from the bundle calculator as part of this PR as well? I think it has some config that we want like using STU3 export instead of R4

It is included in this PR https://github.com/projecttacoma/synthea/pull/1/files

2019-12-04 16:38 UTC, mgramigna approved these changes

2019-12-04 16:39 UTC, merged