Add module for EXM105
projecttacoma/synthea pull request #6
Opened 2020-01-13 17:24 UTC by mgramigna

![image](https://user-images.githubusercontent.com/16297930/72277213-8d31b880-35ff-11ea-98a3-1abdaa892f42.png)

Very similar to the module for EXM104, with a different discharge medication from the ValueSet referenced in the CQL

2020-01-14 15:22 UTC, lukoktonos requested changes
Module generates patients correctly and looks good

As per slack discussion, recommend tweaking probability to speed up calculation a bit as currently it is a bit slow

2020-01-14 18:36 UTC, mgramigna commented
@losborne I updated the delay to be 3 years instead of 1, meaning there is a 90% chance of ischemic stroke every 3 years rather than 1. This seemed to speed up calculation relatively significantly on my end. Let me know if you see the same behavior.

I also upped the probability for the numerator medication being administered since strokes happen less often for this module now.

2020-01-14 19:06 UTC, lukoktonos approved these changes

2020-01-17 17:49 UTC, okeefm approved these changes
Looks good to me. Generates patients with statin meds.

2020-01-17 18:33 UTC, merged